!23
Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    pri(123)
NameError: name 'pri' is not defined
